version: "3"

services:
    openvpn:
        image:  vpnka
        container_name: vpnka
        hostname: vpnka
        cap_add:
        - NET_ADMIN
        - SYS_ADMIN
        devices:
        - /dev/net/tun:/dev/net/tun
        dns:
        - 8.8.8.8
        - 8.8.4.4
        ports:
            - 8888:3128
        volumes:
            - /home/rest/vpn-proxy/vpns:/vpn
        environment:
            - VPN_FILE_NAME=vpnbook-fr1-udp53.ovpn
